class MyKad:
    def __init__(self, mykad):
        self.mykad = mykad
        
    def getBirthPlace(self):
        if self.mykad[6:8] == "01" : return "Johor"
        if self.mykad[6:8] == "21" : return "Johor"
        if self.mykad[6:8] == "22" : return "Johor"
        if self.mykad[6:8] == "23" : return "Johor"
        if self.mykad[6:8] == "24" : return "Johor"
        if self.mykad[6:8] == "02" : return "Kedah"
        if self.mykad[6:8] == "25" : return "Kedah"
        if self.mykad[6:8] == "26" : return "Kedah"
        if self.mykad[6:8] == "27" : return "Kedah"
        if self.mykad[6:8] == "03" : return "Kelantan"
        if self.mykad[6:8] == "28" : return "Kelantan"
        if self.mykad[6:8] == "29 " : return "Kelantan"
        if self.mykad[6:8] == "04" : return "Malacca"
        if self.mykad[6:8] == "30" : return "Malacca"
        if self.mykad[6:8] == "05" : return "Negeri Sembilan"
        if self.mykad[6:8] == "31" : return "Negeri Sembilan"
        if self.mykad[6:8] == "59" : return "Negeri Sembilan"
        if self.mykad[6:8] == "06" : return "Pahang"
        if self.mykad[6:8] == "32" : return "Pahang"
        if self.mykad[6:8] == "33" : return "Pahang"
        if self.mykad[6:8] == "07" : return "Penang"
        if self.mykad[6:8] == "34" : return "Penang"
        if self.mykad[6:8] == "35" : return "Penang"
        if self.mykad[6:8] == "08" : return "Perak"
        if self.mykad[6:8] == "36" : return "Perak"
        if self.mykad[6:8] == "37" : return "Perak"
        if self.mykad[6:8] == "38" : return "Perak"
        if self.mykad[6:8] == "39" : return "Perak"
        if self.mykad[6:8] == "09" : return "Perlis"
        if self.mykad[6:8] == "40" : return "Perlis"
        if self.mykad[6:8] == "10" : return "Selangor"
        if self.mykad[6:8] == "41" : return "Selangor"
        if self.mykad[6:8] == "42" : return "Selangor"
        if self.mykad[6:8] == "43" : return "Selangor"
        if self.mykad[6:8] == "44" : return "Selangor"
        if self.mykad[6:8] == "11" : return "Terengganu"
        if self.mykad[6:8] == "45" : return "Terengganu"
        if self.mykad[6:8] == "46" : return "Terengganu"
        if self.mykad[6:8] == "12" : return "Sabah"
        if self.mykad[6:8] == "47" : return "Sabah"
        if self.mykad[6:8] == "48" : return "Sabah"
        if self.mykad[6:8] == "49" : return "Sabah"
        if self.mykad[6:8] == "13" : return "Sarawak"
        if self.mykad[6:8] == "50" : return "Sarawak"
        if self.mykad[6:8] == "51" : return "Sarawak"
        if self.mykad[6:8] == "52" : return "Sarawak"
        if self.mykad[6:8] == "53" : return "Sarawak"
        if self.mykad[6:8] == "14" : return "Federal Territory of Kuala Lumpur"
        if self.mykad[6:8] == "54" : return "Federal Territory of Kuala Lumpur"
        if self.mykad[6:8] == "55" : return "Federal Territory of Kuala Lumpur"
        if self.mykad[6:8] == "56" : return "Federal Territory of Kuala Lumpur"
        if self.mykad[6:8] == "57" : return "Federal Territory of Kuala Lumpur"
        if self.mykad[6:8] == "15" : return "Federal Territory of Labuan"
        if self.mykad[6:8] == "58" : return "Federal Territory of Labuan"
        if self.mykad[6:8] == "16" : return "Federal Territory of Putrajaya"
        return
        